/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
export type { IAuctionManager } from "./IAuctionManager";
export type { IHarbergerTaxManager } from "./IHarbergerTaxManager";
export type { ILicenceManager } from "./ILicenceManager";
export type { IPublicationManager } from "./IPublicationManager";
export type { IUserManager } from "./IUserManager";
export type { IVault } from "./IVault";
