/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace SharedStructures {
  export type ContributionStruct = {
    contributorAddress: PromiseOrValue<string>;
    weighting: PromiseOrValue<BigNumberish>;
    balance: PromiseOrValue<BigNumberish>;
    lifetimeAllocations: PromiseOrValue<BigNumberish>;
  };

  export type ContributionStructOutput = [
    string,
    number,
    BigNumber,
    BigNumber
  ] & {
    contributorAddress: string;
    weighting: number;
    balance: BigNumber;
    lifetimeAllocations: BigNumber;
  };

  export type CitationStruct = {
    publicationId: PromiseOrValue<BigNumberish>;
    weighting: PromiseOrValue<BigNumberish>;
  };

  export type CitationStructOutput = [BigNumber, number] & {
    publicationId: BigNumber;
    weighting: number;
  };

  export type AuctionStruct = {
    publicationId: PromiseOrValue<BigNumberish>;
    auctionFloor: PromiseOrValue<BigNumberish>;
    startingTime: PromiseOrValue<BigNumberish>;
    duration: PromiseOrValue<BigNumberish>;
    auctionBidIds: PromiseOrValue<BigNumberish>[];
    winningBidId: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type AuctionStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber,
    number
  ] & {
    publicationId: BigNumber;
    auctionFloor: BigNumber;
    startingTime: BigNumber;
    duration: BigNumber;
    auctionBidIds: BigNumber[];
    winningBidId: BigNumber;
    status: number;
  };

  export type BidStruct = {
    commitBid: PromiseOrValue<BytesLike>;
    revealedBid: PromiseOrValue<BigNumberish>;
    revealedSalt: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
    publicationId: PromiseOrValue<BigNumberish>;
    auctionId: PromiseOrValue<BigNumberish>;
    bidderAddress: PromiseOrValue<string>;
  };

  export type BidStructOutput = [
    string,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    string
  ] & {
    commitBid: string;
    revealedBid: BigNumber;
    revealedSalt: BigNumber;
    status: number;
    publicationId: BigNumber;
    auctionId: BigNumber;
    bidderAddress: string;
  };

  export type LicenceStruct = {
    ownerAddress: PromiseOrValue<string>;
    publicationId: PromiseOrValue<BigNumberish>;
    publicationLicenceNo: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type LicenceStructOutput = [string, BigNumber, BigNumber, number] & {
    ownerAddress: string;
    publicationId: BigNumber;
    publicationLicenceNo: BigNumber;
    status: number;
  };

  export type PublicationStruct = {
    pricingStrategy: PromiseOrValue<BigNumberish>;
    publicationUri: PromiseOrValue<string>;
    publicationStatus: PromiseOrValue<BigNumberish>;
    ownerAddress: PromiseOrValue<string>;
    sellPrice: PromiseOrValue<BigNumberish>;
    maxNumberOfLicences: PromiseOrValue<BigNumberish>;
    licencesIssued: PromiseOrValue<BigNumberish>;
    previousVersion: PromiseOrValue<BigNumberish>;
    auctionIds: PromiseOrValue<BigNumberish>[];
    contributionsId: PromiseOrValue<BigNumberish>;
    donations: PromiseOrValue<BigNumberish>[];
    citationsId: PromiseOrValue<BigNumberish>;
    lifetimeEarnings: PromiseOrValue<BigNumberish>;
  };

  export type PublicationStructOutput = [
    number,
    string,
    number,
    string,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber,
    BigNumber[],
    BigNumber,
    BigNumber
  ] & {
    pricingStrategy: number;
    publicationUri: string;
    publicationStatus: number;
    ownerAddress: string;
    sellPrice: BigNumber;
    maxNumberOfLicences: number;
    licencesIssued: BigNumber;
    previousVersion: BigNumber;
    auctionIds: BigNumber[];
    contributionsId: BigNumber;
    donations: BigNumber[];
    citationsId: BigNumber;
    lifetimeEarnings: BigNumber;
  };

  export type TaxObjectStruct = {
    licenceId: PromiseOrValue<BigNumberish>;
    ratePerBlock: PromiseOrValue<BigNumberish>;
    lastPayment: PromiseOrValue<BigNumberish>;
    numberOfOutBids: PromiseOrValue<BigNumberish>;
    currentAssignedValue: PromiseOrValue<BigNumberish>;
    buyOuts: PromiseOrValue<BigNumberish>[];
    status: PromiseOrValue<BigNumberish>;
  };

  export type TaxObjectStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber[],
    number
  ] & {
    licenceId: BigNumber;
    ratePerBlock: BigNumber;
    lastPayment: BigNumber;
    numberOfOutBids: BigNumber;
    currentAssignedValue: BigNumber;
    buyOuts: BigNumber[];
    status: number;
  };
}

export interface UnicoinRegistryInterface extends utils.Interface {
  functions: {
    "buyLicenceFixedRate()": FunctionFragment;
    "canAddressPay(address,uint256)": FunctionFragment;
    "cancelBid(uint256)": FunctionFragment;
    "claimHarbergerTax(uint256)": FunctionFragment;
    "commitSealedBid(bytes32,uint256)": FunctionFragment;
    "createHarbergerBuyOut(uint256,uint256)": FunctionFragment;
    "createPublication(uint8,string,uint256,uint256,uint256,uint256,uint8,(address,uint16,uint256,uint256)[],(uint256,uint16)[])": FunctionFragment;
    "donate(uint256,uint256)": FunctionFragment;
    "finalizeAuction(uint256)": FunctionFragment;
    "finalizeBuyoutOffer(uint256)": FunctionFragment;
    "getAuction(uint256)": FunctionFragment;
    "getAuctionStatus(uint256)": FunctionFragment;
    "getBid(uint256)": FunctionFragment;
    "getBidderBids(address)": FunctionFragment;
    "getBids(address)": FunctionFragment;
    "getBlockTime()": FunctionFragment;
    "getLicence(uint256)": FunctionFragment;
    "getLicenceForAddress(address)": FunctionFragment;
    "getLicenceTaxObjectId(uint256)": FunctionFragment;
    "getMinBuyOutAmount(uint256)": FunctionFragment;
    "getMinBuyOutPrice(uint256)": FunctionFragment;
    "getMostRecentPublicationLicence(uint256)": FunctionFragment;
    "getOutstandingTax(uint256)": FunctionFragment;
    "getPublication(uint256)": FunctionFragment;
    "getPublicationAuctionBidLength(uint256)": FunctionFragment;
    "getPublicationAuctions(uint256)": FunctionFragment;
    "getPublicationBids(uint256)": FunctionFragment;
    "getPublicationContributors(uint256)": FunctionFragment;
    "getPublicationLatestAuction(uint256)": FunctionFragment;
    "getPublicationLength()": FunctionFragment;
    "getPublicationLicences(uint256)": FunctionFragment;
    "getPublicationsAuthorAddress(address)": FunctionFragment;
    "getTaxObject(uint256)": FunctionFragment;
    "getTaxObjectLength()": FunctionFragment;
    "getUserId(address)": FunctionFragment;
    "getUserProfileUri(address)": FunctionFragment;
    "initialize(address,address,address,address,address,address)": FunctionFragment;
    "isCallerRegistered()": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "registerUser(string)": FunctionFragment;
    "revealSealedBid(uint256,uint256,uint256,uint256)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "updateAuctionStartTime(uint256,uint256)": FunctionFragment;
    "updateLicenceHarbergerValuation(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyLicenceFixedRate"
      | "canAddressPay"
      | "cancelBid"
      | "claimHarbergerTax"
      | "commitSealedBid"
      | "createHarbergerBuyOut"
      | "createPublication"
      | "donate"
      | "finalizeAuction"
      | "finalizeBuyoutOffer"
      | "getAuction"
      | "getAuctionStatus"
      | "getBid"
      | "getBidderBids"
      | "getBids"
      | "getBlockTime"
      | "getLicence"
      | "getLicenceForAddress"
      | "getLicenceTaxObjectId"
      | "getMinBuyOutAmount"
      | "getMinBuyOutPrice"
      | "getMostRecentPublicationLicence"
      | "getOutstandingTax"
      | "getPublication"
      | "getPublicationAuctionBidLength"
      | "getPublicationAuctions"
      | "getPublicationBids"
      | "getPublicationContributors"
      | "getPublicationLatestAuction"
      | "getPublicationLength"
      | "getPublicationLicences"
      | "getPublicationsAuthorAddress"
      | "getTaxObject"
      | "getTaxObjectLength"
      | "getUserId"
      | "getUserProfileUri"
      | "initialize"
      | "isCallerRegistered"
      | "isTrustedForwarder"
      | "ownerOf"
      | "registerUser"
      | "revealSealedBid"
      | "setOwner"
      | "updateAuctionStartTime"
      | "updateLicenceHarbergerValuation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyLicenceFixedRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canAddressPay",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimHarbergerTax",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSealedBid",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createHarbergerBuyOut",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createPublication",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      SharedStructures.ContributionStruct[],
      SharedStructures.CitationStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBuyoutOffer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionStatus",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBid",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidderBids",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBids",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLicence",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicenceForAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicenceTaxObjectId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinBuyOutAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinBuyOutPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMostRecentPublicationLicence",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingTax",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublication",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationAuctionBidLength",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationAuctions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationBids",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationContributors",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationLatestAuction",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationLicences",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationsAuthorAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaxObject",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaxObjectLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProfileUri",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isCallerRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revealSealedBid",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAuctionStartTime",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLicenceHarbergerValuation",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyLicenceFixedRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAddressPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimHarbergerTax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitSealedBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createHarbergerBuyOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPublication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBuyoutOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBidderBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLicence", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLicenceForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLicenceTaxObjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinBuyOutAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinBuyOutPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMostRecentPublicationLicence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingTax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationAuctionBidLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationLatestAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationLicences",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationsAuthorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaxObject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaxObjectLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserProfileUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCallerRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealSealedBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAuctionStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLicenceHarbergerValuation",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface UnicoinRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UnicoinRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyLicenceFixedRate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    canAddressPay(
      userAddress: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cancelBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimHarbergerTax(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    commitSealedBid(
      bidHash: PromiseOrValue<BytesLike>,
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createHarbergerBuyOut(
      licenceId: PromiseOrValue<BigNumberish>,
      buyOutAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createPublication(
      _pricingStrategy: PromiseOrValue<BigNumberish>,
      publicationUri: PromiseOrValue<string>,
      auctionFloor: PromiseOrValue<BigNumberish>,
      auctionStartTime: PromiseOrValue<BigNumberish>,
      auctionDuration: PromiseOrValue<BigNumberish>,
      fixedSellPrice: PromiseOrValue<BigNumberish>,
      maxNumberOfLicences: PromiseOrValue<BigNumberish>,
      contributors: SharedStructures.ContributionStruct[],
      citations: SharedStructures.CitationStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    donate(
      publicationId: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    finalizeAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    finalizeBuyoutOffer(
      buyOutId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.AuctionStructOutput]>;

    getAuctionStatus(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.BidStructOutput]>;

    getBidderBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getBlockTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLicence(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.LicenceStructOutput]>;

    getLicenceForAddress(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getLicenceTaxObjectId(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMinBuyOutAmount(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMinBuyOutPrice(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMostRecentPublicationLicence(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOutstandingTax(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPublication(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.PublicationStructOutput]>;

    getPublicationAuctionBidLength(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPublicationAuctions(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getPublicationBids(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getPublicationContributors(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.ContributionStructOutput[]]>;

    getPublicationLatestAuction(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.AuctionStructOutput]>;

    getPublicationLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPublicationLicences(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getPublicationsAuthorAddress(
      authorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getTaxObject(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructures.TaxObjectStructOutput]>;

    getTaxObjectLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserId(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserProfileUri(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      auctionManagerContract: PromiseOrValue<string>,
      licenceManagerContract: PromiseOrValue<string>,
      publicationManagerContract: PromiseOrValue<string>,
      userManagerContract: PromiseOrValue<string>,
      harbergerTaxManagerContract: PromiseOrValue<string>,
      vaultContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isCallerRegistered(overrides?: CallOverrides): Promise<[boolean]>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    registerUser(
      profileUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revealSealedBid(
      bid: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      publicationId: PromiseOrValue<BigNumberish>,
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      ownerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAuctionStartTime(
      publicationId: PromiseOrValue<BigNumberish>,
      newStartTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateLicenceHarbergerValuation(
      licenceId: PromiseOrValue<BigNumberish>,
      newValuation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyLicenceFixedRate(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  canAddressPay(
    userAddress: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  cancelBid(
    bidId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimHarbergerTax(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  commitSealedBid(
    bidHash: PromiseOrValue<BytesLike>,
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createHarbergerBuyOut(
    licenceId: PromiseOrValue<BigNumberish>,
    buyOutAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createPublication(
    _pricingStrategy: PromiseOrValue<BigNumberish>,
    publicationUri: PromiseOrValue<string>,
    auctionFloor: PromiseOrValue<BigNumberish>,
    auctionStartTime: PromiseOrValue<BigNumberish>,
    auctionDuration: PromiseOrValue<BigNumberish>,
    fixedSellPrice: PromiseOrValue<BigNumberish>,
    maxNumberOfLicences: PromiseOrValue<BigNumberish>,
    contributors: SharedStructures.ContributionStruct[],
    citations: SharedStructures.CitationStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  donate(
    publicationId: PromiseOrValue<BigNumberish>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  finalizeAuction(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  finalizeBuyoutOffer(
    buyOutId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAuction(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.AuctionStructOutput>;

  getAuctionStatus(
    auctionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBid(
    bidId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.BidStructOutput>;

  getBidderBids(
    bidderAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getBids(
    bidderAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getBlockTime(overrides?: CallOverrides): Promise<BigNumber>;

  getLicence(
    licenceId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.LicenceStructOutput>;

  getLicenceForAddress(
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getLicenceTaxObjectId(
    licenceId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinBuyOutAmount(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinBuyOutPrice(
    taxObjectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMostRecentPublicationLicence(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOutstandingTax(
    taxObjectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPublication(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.PublicationStructOutput>;

  getPublicationAuctionBidLength(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPublicationAuctions(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getPublicationBids(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getPublicationContributors(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.ContributionStructOutput[]>;

  getPublicationLatestAuction(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.AuctionStructOutput>;

  getPublicationLength(overrides?: CallOverrides): Promise<BigNumber>;

  getPublicationLicences(
    publicationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getPublicationsAuthorAddress(
    authorAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getTaxObject(
    taxObjectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructures.TaxObjectStructOutput>;

  getTaxObjectLength(overrides?: CallOverrides): Promise<BigNumber>;

  getUserId(
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserProfileUri(
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    auctionManagerContract: PromiseOrValue<string>,
    licenceManagerContract: PromiseOrValue<string>,
    publicationManagerContract: PromiseOrValue<string>,
    userManagerContract: PromiseOrValue<string>,
    harbergerTaxManagerContract: PromiseOrValue<string>,
    vaultContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isCallerRegistered(overrides?: CallOverrides): Promise<boolean>;

  isTrustedForwarder(
    forwarder: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  ownerOf(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  registerUser(
    profileUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revealSealedBid(
    bid: PromiseOrValue<BigNumberish>,
    salt: PromiseOrValue<BigNumberish>,
    publicationId: PromiseOrValue<BigNumberish>,
    bidId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    ownerAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAuctionStartTime(
    publicationId: PromiseOrValue<BigNumberish>,
    newStartTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateLicenceHarbergerValuation(
    licenceId: PromiseOrValue<BigNumberish>,
    newValuation: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyLicenceFixedRate(overrides?: CallOverrides): Promise<void>;

    canAddressPay(
      userAddress: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancelBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    claimHarbergerTax(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commitSealedBid(
      bidHash: PromiseOrValue<BytesLike>,
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createHarbergerBuyOut(
      licenceId: PromiseOrValue<BigNumberish>,
      buyOutAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createPublication(
      _pricingStrategy: PromiseOrValue<BigNumberish>,
      publicationUri: PromiseOrValue<string>,
      auctionFloor: PromiseOrValue<BigNumberish>,
      auctionStartTime: PromiseOrValue<BigNumberish>,
      auctionDuration: PromiseOrValue<BigNumberish>,
      fixedSellPrice: PromiseOrValue<BigNumberish>,
      maxNumberOfLicences: PromiseOrValue<BigNumberish>,
      contributors: SharedStructures.ContributionStruct[],
      citations: SharedStructures.CitationStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    donate(
      publicationId: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    finalizeBuyoutOffer(
      buyOutId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.AuctionStructOutput>;

    getAuctionStatus(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.BidStructOutput>;

    getBidderBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getBlockTime(overrides?: CallOverrides): Promise<BigNumber>;

    getLicence(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.LicenceStructOutput>;

    getLicenceForAddress(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getLicenceTaxObjectId(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBuyOutAmount(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBuyOutPrice(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMostRecentPublicationLicence(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOutstandingTax(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublication(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.PublicationStructOutput>;

    getPublicationAuctionBidLength(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationAuctions(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getPublicationBids(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getPublicationContributors(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.ContributionStructOutput[]>;

    getPublicationLatestAuction(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.AuctionStructOutput>;

    getPublicationLength(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicationLicences(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getPublicationsAuthorAddress(
      authorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getTaxObject(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructures.TaxObjectStructOutput>;

    getTaxObjectLength(overrides?: CallOverrides): Promise<BigNumber>;

    getUserId(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProfileUri(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      auctionManagerContract: PromiseOrValue<string>,
      licenceManagerContract: PromiseOrValue<string>,
      publicationManagerContract: PromiseOrValue<string>,
      userManagerContract: PromiseOrValue<string>,
      harbergerTaxManagerContract: PromiseOrValue<string>,
      vaultContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isCallerRegistered(overrides?: CallOverrides): Promise<boolean>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerUser(
      profileUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revealSealedBid(
      bid: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      publicationId: PromiseOrValue<BigNumberish>,
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(
      ownerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAuctionStartTime(
      publicationId: PromiseOrValue<BigNumberish>,
      newStartTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLicenceHarbergerValuation(
      licenceId: PromiseOrValue<BigNumberish>,
      newValuation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    buyLicenceFixedRate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    canAddressPay(
      userAddress: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimHarbergerTax(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    commitSealedBid(
      bidHash: PromiseOrValue<BytesLike>,
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createHarbergerBuyOut(
      licenceId: PromiseOrValue<BigNumberish>,
      buyOutAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createPublication(
      _pricingStrategy: PromiseOrValue<BigNumberish>,
      publicationUri: PromiseOrValue<string>,
      auctionFloor: PromiseOrValue<BigNumberish>,
      auctionStartTime: PromiseOrValue<BigNumberish>,
      auctionDuration: PromiseOrValue<BigNumberish>,
      fixedSellPrice: PromiseOrValue<BigNumberish>,
      maxNumberOfLicences: PromiseOrValue<BigNumberish>,
      contributors: SharedStructures.ContributionStruct[],
      citations: SharedStructures.CitationStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    donate(
      publicationId: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    finalizeAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    finalizeBuyoutOffer(
      buyOutId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuctionStatus(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidderBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBlockTime(overrides?: CallOverrides): Promise<BigNumber>;

    getLicence(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLicenceForAddress(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLicenceTaxObjectId(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBuyOutAmount(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinBuyOutPrice(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMostRecentPublicationLicence(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOutstandingTax(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublication(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationAuctionBidLength(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationAuctions(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationBids(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationContributors(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationLatestAuction(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationLength(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicationLicences(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPublicationsAuthorAddress(
      authorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTaxObject(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTaxObjectLength(overrides?: CallOverrides): Promise<BigNumber>;

    getUserId(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserProfileUri(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      auctionManagerContract: PromiseOrValue<string>,
      licenceManagerContract: PromiseOrValue<string>,
      publicationManagerContract: PromiseOrValue<string>,
      userManagerContract: PromiseOrValue<string>,
      harbergerTaxManagerContract: PromiseOrValue<string>,
      vaultContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isCallerRegistered(overrides?: CallOverrides): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerUser(
      profileUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revealSealedBid(
      bid: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      publicationId: PromiseOrValue<BigNumberish>,
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOwner(
      ownerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAuctionStartTime(
      publicationId: PromiseOrValue<BigNumberish>,
      newStartTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateLicenceHarbergerValuation(
      licenceId: PromiseOrValue<BigNumberish>,
      newValuation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyLicenceFixedRate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    canAddressPay(
      userAddress: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimHarbergerTax(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    commitSealedBid(
      bidHash: PromiseOrValue<BytesLike>,
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createHarbergerBuyOut(
      licenceId: PromiseOrValue<BigNumberish>,
      buyOutAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createPublication(
      _pricingStrategy: PromiseOrValue<BigNumberish>,
      publicationUri: PromiseOrValue<string>,
      auctionFloor: PromiseOrValue<BigNumberish>,
      auctionStartTime: PromiseOrValue<BigNumberish>,
      auctionDuration: PromiseOrValue<BigNumberish>,
      fixedSellPrice: PromiseOrValue<BigNumberish>,
      maxNumberOfLicences: PromiseOrValue<BigNumberish>,
      contributors: SharedStructures.ContributionStruct[],
      citations: SharedStructures.CitationStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    donate(
      publicationId: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    finalizeAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    finalizeBuyoutOffer(
      buyOutId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAuction(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuctionStatus(
      auctionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBid(
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBidderBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBids(
      bidderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBlockTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLicence(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLicenceForAddress(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLicenceTaxObjectId(
      licenceId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinBuyOutAmount(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinBuyOutPrice(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMostRecentPublicationLicence(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOutstandingTax(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublication(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationAuctionBidLength(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationAuctions(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationBids(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationContributors(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationLatestAuction(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationLicences(
      publicationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPublicationsAuthorAddress(
      authorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTaxObject(
      taxObjectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTaxObjectLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserId(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserProfileUri(
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      auctionManagerContract: PromiseOrValue<string>,
      licenceManagerContract: PromiseOrValue<string>,
      publicationManagerContract: PromiseOrValue<string>,
      userManagerContract: PromiseOrValue<string>,
      harbergerTaxManagerContract: PromiseOrValue<string>,
      vaultContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isCallerRegistered(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerUser(
      profileUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revealSealedBid(
      bid: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      publicationId: PromiseOrValue<BigNumberish>,
      bidId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      ownerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAuctionStartTime(
      publicationId: PromiseOrValue<BigNumberish>,
      newStartTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateLicenceHarbergerValuation(
      licenceId: PromiseOrValue<BigNumberish>,
      newValuation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
